-- AlterTable
ALTER TABLE "LeagueTeam" ADD COLUMN "draws" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeagueTeam" ADD COLUMN "roundsWon" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeagueTeam" ADD COLUMN "roundsLost" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Match" ADD COLUMN "team1Rounds" INTEGER;
ALTER TABLE "Match" ADD COLUMN "team2Rounds" INTEGER;
