-- AlterTable
ALTER TABLE "Demo" ADD COLUMN "isManual" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Demo" ALTER COLUMN "filePath" DROP NOT NULL;
ALTER TABLE "Demo" ALTER COLUMN "fileName" DROP NOT NULL;

-- AlterTable
ALTER TABLE "MatchPlayerStat" ADD COLUMN "teamId" TEXT;
ALTER TABLE "MatchPlayerStat" ADD COLUMN "assists" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerStat" ADD COLUMN "damage" INTEGER NOT NULL DEFAULT 0;
